### ISSUE TITLE
Add an option to disable auto-format

### ISSUE THREAD

**Issue by FantasqueX** [neocmakelsp/neocmakelsp-vscode#20]
Sometimes, I just want to change a little bit of other's project and don't want to touch their styles. If there is an option to disable auto-formatting in workspace, it will be awesome!

**Comment by FantasqueX** [comment]
What's more, I think auto-formatting should be disabled by default.

**Comment by Decodetalkers** [comment]
this plugin do not do anything when file is saved.. It does not do anything to run auto-format.. and I try it on my code-oss, the auto-format did not happened.. maybe there is anyother plugin do the lsp format when file is changed?

**Comment by FantasqueX** [comment]
Sorry, I didn't realize I enable `editor.formatOnSave`
