### ISSUE TITLE
no code completion;no Hover

### ISSUE THREAD

**Issue by digitama6512** [neocmakelsp/neocmakelsp-vscode#40]
## Environment
OS: 6.8.0-48-generic Ubuntu22.04.5LTS GNOME42.9
neocmakelsp: 0.0.14
vscode: 1.95.3

## no code completion
![no code completion](https://github.com/user-attachments/assets/5cf19424-4fe7-48e6-8e13-8d6d8d3e7add)

## no Hover
![no Hover](https://github.com/user-attachments/assets/83ae756d-309b-493e-a8af-a41f5ffe9510)

**Comment by Decodetalkers** [comment]
Have you installed cmake?

**Comment by digitama6512** [comment]
> Have you installed cmake?

Sorry, I forget to close this issue, just because my cmake is broken.

**Comment by digitama6512** [comment]
Please check your cmake.
