### ISSUE TITLE
"Go to Definition" jumps to the wrong file

### ISSUE THREAD

**Issue by oltolm** [neocmakelsp/neocmakelsp-vscode#49]
Here is a simple project to reproduce.

`CMakeLists.txt` in the project directory:
```
cmake_minimum_required(VERSION 3.17.2)
project(Vita3K)

add_subdirectory(subdir)

macro(get_boost)
endmacro()

```
`CMakeLists.txt` in `subdir`
```
get_boost()
#
#
#
#
#
#
```

If you place the cursor at `get_boost` and press F12 it should jump to the macro definition, but it does not. It jumps to line 6 in the same file. It is important to open `subdir\CMakeLists.txt` only. If you also open the `CMakeLists.txt` in the project folder then it will work.

**Comment by Decodetalkers** [comment]
It is designed like this.. when it comes to jump to file, the context relay on opening the file to get the file to get the reference position, only if when you open that file, neocmakelsp can know the function position in other file. 

Emm.. I can realize this feature.. wait for some time.. but then it will take more time to initialize

**Comment by Decodetalkers** [comment]
please try these release

**Comment by oltolm** [comment]
It works now, thanks for the fast fix.
